### ISSUE TITLE
pip install pycompat failed in i686 

### ISSUE THREAD

**Issue by sergiomb2** [alexandrevicenzi/pycompat#5]
pip install pycompat
You are using pip version 7.1.0, however version 7.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Collecting pycompat
  Downloading pycompat-0.2.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-Agpz_U/pycompat/setup.py", line 10, in <module>
        with open('LICENSE') as f:
    IOError: [Errno 2] No such file or directory: 'LICENSE'

**Comment by alexandrevicenzi** [comment]
@sergiomb2 what OS and Python version are you using?

**Comment by sergiomb2** [comment]
Linux Fedora 23 
python-2.7.10-8.fc23.i686

**Comment by thorstenkampe** [comment]
The package does not contain a license file - will the easy to fix bug be fixed?

**Comment by alexandrevicenzi** [comment]
Yeah, sure, just run:

 `pip install -e git+git://github.com/alexandrevicenzi/pycompat.git#egg=pycompat`

It wil work until fixing the package on PyPi

**Comment by sergiomb2** [comment]
so it is fixed ? in next version ?

**Comment by thorstenkampe** [comment]
Alexandre,
thanks for the fast response. I hope this means that the package is still maintained.

**Comment by alexandrevicenzi** [comment]
Not sure if it's fixed, I need to check it out what wrong with the package on PyPi.

I'll take a look this week.

**Comment by alexandrevicenzi** [comment]
Fixed in 0.3.0.

**Comment by sergiomb2** [comment]
I could confirm the fix , thanks.
